devices/urls.py
from django.urls import include, path

from . import views 


app_name = "devices"

# -----------------------------------------------------------------------------
# Device URLs
# -----------------------------------------------------------------------------
device_edit_urls = [
    # details view
    path("details/", views.DeviceDetailView.as_view(), name="device_details"),
    
    # edit view
    path("edit/", views.DeviceEditView.as_view(), name="device_edit"),
    
    # delete view
    path("delete/", views.DeviceDeleteView.as_view(), name="device_delete"),
    
    # device data list
    path("data/", views.DeviceDataHistoryView.as_view(), name="device_data_list"),
]

device_urls = [
    # create view
    path("create/", views.DeviceCreateView.as_view(), name="device_create"),
    
    # list view
    path("list/", views.DeviceListView.as_view(), name="device_list"),
    
    # details, edit, remove and deactivate views
    path("<slug:device_uid>/",  include(device_edit_urls)),
]

# -----------------------------------------------------------------------------
# Device Group URLs
# -----------------------------------------------------------------------------
group_edit_urlpatterns = [
    # details view
    path("details/", views.DeviceGroupDetailView.as_view(), name="group_details"),
    
    # edit view
    path("edit/", views.DeviceGroupEditView.as_view(), name="group_edit"),
    
    # delete view
    path("delete/", views.DeviceGroupDeleteView.as_view(), name="group_delete"),
]

group_urls = [
    
    # create view
    path("create/", views.DeviceGroupCreateView.as_view(), name="group_create"),
    
    # list view
    path("list/", views.DeviceGroupListView.as_view(), name="group_list"),
    
    # details, edit and remove views
    path("<slug:group_name>/", include(group_edit_urlpatterns)),
]

# -----------------------------------------------------------------------------
# Device Data URLs
# -----------------------------------------------------------------------------
device_data = [
    path("<int:pk>/", views.DeviceDataDetailsView.as_view(), name="data_details"),
    path("list/", views.DeviceDataListView.as_view(), name="data_list"),
]

# -----------------------------------------------------------------------------
# Device Application URLs
# -----------------------------------------------------------------------------
urlpatterns = [
    path("", include(device_urls)),
    path("group/", include(group_urls)),
    path("data/", include(device_data)),
    path("search/", views.DeviceSearchResultsView.as_view(), name="search"),
]

sia/urls.py
from django.contrib import admin
from django.urls import include, path

from dashboard import views as dashboard_views


urlpatterns = [
    # admin
    path("admin/", admin.site.urls),
    
    # accounts
    path("accounts/", include("accounts.urls")),

    # devices
    path("device/", include("devices.urls")),
    
    # dashboard
    path("dashboard", include("dashboard.urls")),

    # debug toolbar 
    path('__debug__/', include('debug_toolbar.urls')),
    
    # homepage
    path("", dashboard_views.DashboardView.as_view(), name="homepage"),
]

devices/forms.py
from distutils.command import clean
from typing import *

from django.db.models import TextChoices
from django.forms import ModelChoiceField, ModelForm, Form, CharField, ChoiceField
from django.utils.translation import gettext_lazy as _

from common.forms.mixins import (UniqueDeviceGroupPerMemberMixin,
                                    UniqueDevicePerMemberMixin)

from .models import Device, DeviceGroup

# Create your views here.


# -----------------------------------------------------------------------
# device group forms
# -----------------------------------------------------------------------
class BaseDeviceGroupForm(UniqueDeviceGroupPerMemberMixin, ModelForm):
    class Meta:
        model = DeviceGroup
        fields = [
            "name",
            "description"
        ]
        
    def __init__(self, *args, **kwargs):
        self.owner = kwargs.pop("member")
        super().__init__(*args, **kwargs)


class DeviceGroupCreateForm(BaseDeviceGroupForm):
    """Form to create a new device group"""
    def save(self, commit: bool = True) -> Any:
        self.instance.owner = self.owner
        return super().save(commit)


class DeviceGroupEditForm(BaseDeviceGroupForm):
    """Device group edit form"""
    def save(self, commit: bool = True) -> Any:
        """Save only if data was changed"""
        if self.changed_data:
            return super().save(commit)
        return super().save(False)


# -----------------------------------------------------------------------
# device forms
# -----------------------------------------------------------------------
class BaseDeviceForm(UniqueDevicePerMemberMixin, ModelForm):
    group = ModelChoiceField(
        queryset=DeviceGroup.objects.all(),
    )
    
    class Meta:
        model = Device
        fields = [
            "name",
        ]
    
    def __init__(self, *args, **kwargs):
        self.owner = kwargs.pop("member")
        super().__init__(*args, **kwargs)
        self.fields["group"].queryset = self.owner.devicegroup_set.all()


class DeviceCreateForm(BaseDeviceForm):
    """Form to create a new device"""
    def save(self, commit: bool = True) -> Any:
        device_group = self.owner.devicegroup_set.get(name=self.cleaned_data["group"])
        device_unique_id = f"{self.owner.username}-{device_group.name}-{self.instance.name}"
        self.instance.group = device_group
        self.instance.uid = Device.generate_device_uid(device_unique_id)
        return super().save(commit)


class DeviceEditForm(BaseDeviceForm):
    """Form to edit an existing device"""
    
    class Meta(BaseDeviceForm.Meta):
        fields = BaseDeviceForm.Meta.fields + [
            "group",
            "is_active",
        ]


# -----------------------------------------------------------------------
# Search form
# -----------------------------------------------------------------------
class DeviceSearchForm(Form):
    class SearchFor(TextChoices):
        DEVICE = "device", _("Device")
        GROUP = "group", _("Group")
        
    """Form to search for devices, or device groups"""
    name = CharField(
        max_length=100, 
        label=_("Name"),
        required=False,
    )
    
    search_for = ChoiceField(
        choices=SearchFor.choices, 
        label=_("Search For"), 
        required=False, 
        initial=SearchFor.DEVICE,
    )
    
    def clean_name(self) -> str:
        """Validate name"""
        name = self.cleaned_data["name"]
        if name:
            return name.strip()
        return name.lower()

devices/views.py
from typing import *

from django.conf import settings
from django.core.paginator import InvalidPage, Paginator
from django.db.models import Count, F, Q, QuerySet
from django.db.models.query import QuerySet
from django.http import Http404, HttpRequest, HttpResponse
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import DetailView, ListView
from django.views.generic.edit import (CreateView, DeleteView, FormView,
                                        UpdateView)

from accounts.forms import MemberConfirmActionForm
from common.views.mixins import MemberLoginRequiredMixin

from .forms import (DeviceCreateForm, DeviceEditForm, DeviceGroupCreateForm,
                    DeviceGroupEditForm, DeviceSearchForm)
from .models import Device, DeviceData, DeviceGroup

# Create your views here.

class SearchBarMixin:
    extra_context = dict(
        search_form=DeviceSearchForm(),
    )


# -----------------------------------------------------------------------
# Device Group Mixins
# -----------------------------------------------------------------------
class DeviceGroupByOwnerMixin:
    
    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(owner=self.request.user)


# -----------------------------------------------------------------------
# Device Mixins
# -----------------------------------------------------------------------
class DevicesByOwnerMixin:
    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(group__owner=self.request.user)


class DeviceBySlugMixin(DevicesByOwnerMixin):
    slug_field = "uid"
    slug_url_kwarg = "device_uid"


# -----------------------------------------------------------------------
# Base device group views
# -----------------------------------------------------------------------
class BaseDeviceGroupView(MemberLoginRequiredMixin, SearchBarMixin, DeviceGroupByOwnerMixin):
    model = DeviceGroup

    def get_form_kwargs(self) -> Dict[str, Any]:
        """Add owner to form kwargs"""
        kwargs = super().get_form_kwargs()
        kwargs["member"] = self.request.user
        return kwargs


class BaseDeviceGroupBySlugView(BaseDeviceGroupView):
    slug_field = "name"
    slug_url_kwarg = "group_name"


class BaseDeviceGroupEditView(BaseDeviceGroupBySlugView):
    extra_context = None


# -----------------------------------------------------------------------
# device group views
# -----------------------------------------------------------------------
class DeviceGroupCreateView(BaseDeviceGroupView, CreateView):
    """Create a new device group"""
    form_class = DeviceGroupCreateForm
    template_name = "devices/group/create.html"
    extra_context = None


class DeviceGroupListView(BaseDeviceGroupView, ListView):
    """List all device groups for the current user"""
    context_object_name = "device_groups"
    template_name = "devices/group/list.html"
    allow_empty = True
    paginate_by = settings.PAGINATION_SIZE
    
    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        return qs.annotate(device_count=Count("device"))


class DeviceGroupDetailView(BaseDeviceGroupBySlugView, DetailView):
    """Details view for a device group"""
    template_name = "devices/group/details.html"
    context_object_name = "device_group"
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["device_count"] = self.object.device_set.count()
        context["device_list"] = self.object.device_set.all()
        return context


class DeviceGroupEditView(BaseDeviceGroupEditView, UpdateView):
    """Device group edit view"""
    form_class = DeviceGroupEditForm
    template_name = "devices/group/edit.html"
    context_object_name = "device_group"


class DeviceGroupDeleteView(BaseDeviceGroupEditView, DeleteView):
    """Delete device group"""
    form_class = MemberConfirmActionForm
    template_name = "devices/group/delete.html"
    success_url = reverse_lazy("devices:group_list")
    context_object_name = "device_group"


# -----------------------------------------------------------------------
# Base Device views
# -----------------------------------------------------------------------
class BaseDeviceView(MemberLoginRequiredMixin, SearchBarMixin):
    model = Device 


class BaseDeviceWithMemberFormView(BaseDeviceView):
    def get_form_kwargs(self) -> Dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs["member"] = self.request.user
        return kwargs


class BaseDeviceBySlugDetailsView(BaseDeviceView, DeviceBySlugMixin):
    ...


class BaseDeviceBySlugEditView(BaseDeviceWithMemberFormView, DeviceBySlugMixin):
    extra_context = None


# -----------------------------------------------------------------------
# Device views
# -----------------------------------------------------------------------
class DeviceCreateView(BaseDeviceWithMemberFormView, CreateView):
    form_class = DeviceCreateForm
    template_name = "devices/device/create.html"


class DeviceListView(BaseDeviceView, DevicesByOwnerMixin, ListView):
    fields = [
        'name', 
        "uid",
        'group',
        'owner',
        'date_added',
        'last_updated',
        'is_active'
    ]
    template_name = 'devices/device/list.html'
    context_object_name = 'device_list'
    paginate_by = settings.PAGINATION_SIZE
    
    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset().filter(is_active=True).annotate(
            group_name=F("group__name"),
            owner_name=F("group__owner__username"),
        ).order_by("group_name", "name")
        return qs


class DeviceDetailView(BaseDeviceBySlugDetailsView, DetailView):
    fields = [
        "name",
        "uid",
        "date_added",
        "group",
        "is_active",
    ]

    template_name = "devices/device/details.html"
    context_object_name = "device"
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context_data =  super().get_context_data(**kwargs)
        context_data["device_group"] = self.object.group
        context_data["device_owner"] = self.object.group.owner
        context_data["device_data_list"] = self.object.devicedata_set.all().order_by("-date")[:settings.MOST_RECENT_SIZE]
        last_data = context_data["device_data_list"].first()
        context_data["last_update"] = last_data.date if last_data else None
        return context_data


class DeviceEditView(BaseDeviceBySlugEditView, UpdateView):
    form_class = DeviceEditForm
    template_name = "devices/device/edit.html"


class DeviceDeleteView(BaseDeviceBySlugEditView, DeleteView):
    form_class = MemberConfirmActionForm
    template_name = "devices/device/delete.html"
    success_url = reverse_lazy("devices:device_list")


class DeviceDataHistoryView(BaseDeviceBySlugDetailsView, ListView):
    template_name = "devices/device/data_history.html"
    context_object_name = "device_data_list"
    paginate_by = settings.PAGINATION_SIZE
    
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.device = get_object_or_404(Device, uid=kwargs["device_uid"], group__owner=request.user)
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["device"] = self.device
        return context
    
    def get_queryset(self) -> QuerySet[Any]:
        return self.device.devicedata_set.all().order_by("-date")


# -----------------------------------------------------------------------
# Device Data views
# -----------------------------------------------------------------------
class BaseDeviceDataView(MemberLoginRequiredMixin, SearchBarMixin):
    model = DeviceData


class DeviceDataByMember(BaseDeviceDataView):
    def get_queryset(self) -> QuerySet[Any]:
        # TODO active devices only
        device_member_filter = Q(device__group__owner=self.request.user) # & Q(device__is_active=True)
        return super().get_queryset().filter(device_member_filter)


class DeviceDataDetailsView(DeviceDataByMember, DetailView):
    template_name = "devices/data/details.html"
    context_object_name = "device_data"


class DeviceDataListView(DeviceDataByMember, ListView):
    template_name = "devices/data/list.html"
    context_object_name = "device_data_list"
    ordering = ["-date"]
    paginate_by = settings.PAGINATION_SIZE


# -----------------------------------------------------------------------
# DeviceGroup/Device Search View
# -----------------------------------------------------------------------
class DeviceSearchResultsView(MemberLoginRequiredMixin, FormView):
    form_class = DeviceSearchForm
    paginate_by = settings.PAGINATION_SIZE
    allow_empty = True
    queryset = None
    model = Device
    paginate_orphans = 0
    paginator_class = Paginator
    page_kwarg = "page"
    context_object_name = "search_results"
    ordering = ["name"]
    template_name = "devices/search.html"
    
    
    def get_queryset(self):
        search_for = self.request.GET.get("search_for", None)
        name = self.request.GET.get("name", None)
        
        if search_for is None or name is None:
            return Device.objects.none()
        
        if search_for == DeviceSearchForm.SearchFor.DEVICE:
            self.queryset = Device.objects.filter(group__owner=self.request.user, name__icontains=name)
        else:
            self.queryset = DeviceGroup.objects.filter(owner=self.request.user, name__icontains=name)
        
        queryset = self.queryset.all()
        
        ordering = self.ordering
        queryset = queryset.order_by(*ordering)

        return queryset
    

devices/templates/devices/device/create.html
{% extends 'base/base_page.html' %}

{% comment %} devices/create_device.html {% endcomment %}

{% block title %}Create Device{% endblock title %}

{% block body %}

<h1>Create New Device</h1>

<div class="form_container">
  <form method="post">
    {% csrf_token %}
    
    <table>
      {{ form.as_table }}
    </table>
    
    <br>
    <div>
      <button type="submit">Create Device</button>
    </div>

    <br>
    <div>
      <button type="reset">Clear</button>
    </div>

    <br>
    <div>
      <button type="button" onclick="window.location.href = '{% url 'devices:device_list' %}'">Cancel</button>
    </div>

  </form>
</div>

{% endblock body %}

devices/templates/devices/device/data_history.html
{% extends 'base/base_page.html' %}

{% block title %}Device Data{% endblock title %}

{% block body %}
<h1>Data History</h1>

<section>

  {% if device_data_list %}
  
  <ul>
  {% for device_data in device_data_list %}
    <li>
      {% include 'devices/device_data.html' %}
    </li>
    {% endfor %}
  </ul>

  {% else %}
  
  <p>
    The device has not sent any data yet.
  </p>

  {% endif %}

</section>

<section>
  <div>
    <a href="{% url 'devices:device_details' device.uid %}">Device Details</a>
  </div>
  <br>
</section>

<hr>

<section class="pagination">
  {% include 'base/base_pagination.html' %}
</section>


{% endblock body %}

devices/templates/devices/device/delete.html
{% extends 'base/base_page.html' %}

{% block title %}Delete Device{% endblock title %}

{% block body %}

<h1>Delete Device</h1>

<section>
  <p>
    <strong>
      Are you sure you want to delete the device: {{ device.name }}? 
    </strong>
  </p>

  <p>
    This operation can't be undone. When the device is deleted, all its saved data are removed as well.
  </p>

  <p>
    If you don't want to delete the device, but still want it to be hidden from the list, you can deactivate it instead from <a href="{% url 'devices:device_edit' device.uid %}">here</a>
  </p>
  
</section>

<section>
  <div class="form-container">
    <form action="{% url 'devices:device_delete' device.uid %}" method="post">
      
      {% csrf_token %}

      <table>
        {{ form.as_table }}
      </table>

      <br>
      <div>
        <button type="submit">Delete</button>
      </div>
      
      <br>
      <div>
        <button type="button" onclick="window.location.href='{% url 'devices:device_details' device.uid %}'">Cancel</button>
      </div>
      
    </form>
  </div>



</section>

{% endblock body %}

devices/templates/devices/device/details.html
{% extends 'base/base_page.html' %}

{% comment %}devices/device_details.html{% endcomment %}

{% block title %}Device Details{% endblock title %}

{% block body %}
<h1>Device {{ device.name }} </h1>

<section>
  
  <hr>
  {% include 'devices/device_details.html' %}
  <hr>

  <div>
    <a href="{% url 'devices:device_data_list' device.uid %}">Device Data</a>
  </div>
  <br>

  <div>
    <a href="{% url 'devices:device_edit' device.uid %}">Edit Device</a>
  </div>
  <br>
  
  </div>
    <a href="{% url 'devices:device_delete' device.uid %}" class="btn btn-danger">Delete Device</a>
  </div>
  <br>

</section>
{% endblock body %}

devices/templates/devices/device/edit.html
{% extends 'base/base_page.html' %}

{% block title %}Edit Device{% endblock title %}

{% block body %}

<h1>Edit Device</h1>

<section>

  <div class="form-container">
    <form method="post">
      {% csrf_token %}

      <table>
        {{ form.as_table }}
      </table>

      <br>
      <div>
        <button type="submit">Save</button>
      </div>

      <br>
      <div>
        <button type="reset">Reset</button>
      </div>

      <br>
      <div>
        <button type="button" onclick="window.location.href='{% url 'devices:device_details' device.uid %}'">Cancel</button>
      </div>


    </form>
  </div>


</section>

{% endblock body %}

devices/templates/devices/device/list.html
{% extends 'base/base_page.html' %}

{% block title %}Device List{% endblock title %}

{% block body %}

<section>

  <h1>My Devices</h1>

  <div class="details-container">

    {% if device_list %}

      <ul>

        {% for device in device_list  %}
        
        <li>
          <a href="{% url 'devices:device_details' device.uid %}">{{ device.name }}</a>
        </li>
        
        
        {% endfor %}
      </ul>

    
    {% else %}

    <p>
      You don't have any devices yet.
    </p>
    
    {% endif %}

  </div>

</section>

<section>
  {% include 'base/base_pagination.html' %}
</section>

<section>
  <br>
  <div>
    <a href="{% url 'devices:device_create' %}">Add Device</a>
  </div>
</section>


{% endblock %}